### ISSUE TITLE
Support of .Net 3.5? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [MineLib/ProtocolModern_1.7.10#1]
Hi,
First I am really appreciated that u made such a great library for the community. But I got some problems using it since it is using .Net framework 4.5 so will it be possible to port it to .Net 3.5?

**Comment by Aragas** [comment]
Thanks!
Well, the minimal version is 4.0. The problem is, 3.5 doesn't support portable profile. But I'm pretty sure it will work if you'll make a specific 3.5 library project.

**Comment by DefinitlyEvil** [comment]
Will it be possible for you to do that for me because I am kinda nooby with C# as I haven't been using C# for years. xD

**Comment by Aragas** [comment]
Are you sure you can't use 4.0? There are no more problems with that. WinXP supports it, Unix (OS X included) supports it, Xamarin too. Can you be more specific with your usage?

**Comment by DefinitlyEvil** [comment]
Unity3D only supports Mono 2.0 and 3.5 so... xD

**Comment by Aragas** [comment]
I'm using code that unity supports with problems. The only way is to modify the code yourself. I can't make my library work on unity, it has too much limits.  
e.g. Assembly.Load

**Comment by DefinitlyEvil** [comment]
okay thx anyways. :( I guess I gotta spend months on it from now on. xD

**Comment by Aragas** [comment]
I'm sure it won't be hard. Just include assemblies instead of dynamically loading them
